# Generated by Django 2.2.2 on 2020-01-12 13:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mathitis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('onoma', models.CharField(blank=True, default='', max_length=100, verbose_name='Ονομα και επώνυμο ')),
                ('tmima', models.CharField(blank=True, default='', max_length=100, verbose_name='Τμήμα')),
                ('mathima', models.CharField(blank=True, default='', max_length=100, verbose_name='Μαθημα')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Μαθητής',
                'verbose_name_plural': 'Μαθητές',
                'ordering': ('onoma',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giamathiti4', models.CharField(choices=[('sae', 'ΣΥΣΤΗΜΑΤΑ ΑΥΤΟΚΙΝΗΤΟΥ'), ('psiksi', 'ΨΥΞΗ ΚΑΙ ΚΛΙΜΑΤΙΣΜΟΣ'), ('ergaliomihanes', 'ΕΡΓΑΛΕΙΟΜΗΧΑΝΕΣ')], default='sae', max_length=6)),
                ('date_links', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, default='', max_length=100, verbose_name='Σύνδεσμος ')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('date_links',),
            },
        ),
        migrations.CreateModel(
            name='simiosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giamathiti3', models.CharField(choices=[('sae', 'ΣΥΣΤΗΜΑΤΑ ΑΥΤΟΚΙΝΗΤΟΥ'), ('psiksi', 'ΨΥΞΗ ΚΑΙ ΚΛΙΜΑΤΙΣΜΟΣ'), ('ergaliomihanes', 'ΕΡΓΑΛΕΙΟΜΗΧΑΝΕΣ')], default='sae', max_length=6)),
                ('date_simiosis', models.DateField(blank=True, null=True)),
                ('simiosi', models.FileField(blank=True, upload_to='techbook/static/simiosis')),
            ],
            options={
                'verbose_name': 'Σημείωση',
                'verbose_name_plural': 'Σημειώσεις',
                'ordering': ('date_simiosis',),
            },
        ),
        migrations.CreateModel(
            name='epidosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giamathima', models.CharField(choices=[('sae', 'ΣΥΣΤΗΜΑΤΑ ΑΥΤΟΚΙΝΗΤΟΥ'), ('psiksi', 'ΨΥΞΗ ΚΑΙ ΚΛΙΜΑΤΙΣΜΟΣ'), ('ergaliomihanes', 'ΕΡΓΑΛΕΙΟΜΗΧΑΝΕΣ')], default='sae', max_length=6, verbose_name='Μάθημα')),
                ('date_epidosis', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία')),
                ('epidosi', models.IntegerField(default='', null=True, verbose_name='Επίδοση')),
                ('eidos', models.CharField(choices=[('pb', 'ΠΡΟΦΟΡΙΚΟΣ'), ('gp', 'ΓΡΑΠΤΟΣ'), ('diagonisma', 'ΔΙΑΓΩΝΙΣΜΑ'), ('eksetasis', 'ΕΞΕΤΑΣΕΙΣ')], default='pb', max_length=6)),
                ('giamathiti2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Επίδοση',
                'verbose_name_plural': 'Επιδόσεις',
                'ordering': ('date_epidosis',),
            },
        ),
        migrations.CreateModel(
            name='apusies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_apusias', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία')),
                ('no_apusion', models.IntegerField(default='', null=True, verbose_name='Απουσίες')),
                ('giamathiti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Απουσία',
                'verbose_name_plural': 'Απουσίες',
                'ordering': ('date_apusias',),
            },
        ),
    ]
