# Generated by Django 2.2.2 on 2020-01-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathitis',
            name='prosopiko_minima',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Προσωπικό Μήνυμα'),
        ),
        migrations.AlterField(
            model_name='epidosis',
            name='eidos',
            field=models.CharField(choices=[('pb', 'ΠΡΟΦΟΡΙΚΟΣ'), ('gp', 'ΓΡΑΠΤΟΣ'), ('diagonisma', 'ΔΙΑΓΩΝΙΣΜΑ'), ('eksetasis', 'ΕΞΕΤΑΣΕΙΣ')], default='pb', max_length=66),
        ),
        migrations.AlterField(
            model_name='links',
            name='giamathiti4',
            field=models.CharField(choices=[('sae', 'ΣΥΣΤΗΜΑΤΑ ΑΥΤΟΚΙΝΗΤΟΥ'), ('psiksi', 'ΨΥΞΗ ΚΑΙ ΚΛΙΜΑΤΙΣΜΟΣ'), ('ergaliomihanes', 'ΕΡΓΑΛΕΙΟΜΗΧΑΝΕΣ')], default='sae', max_length=116),
        ),
    ]
